language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install pdoc3==0.9.1

# command to run tests
script:
 - coverage run -m unittest discover --pattern *_test.py

after_success:
 - bash <(curl -s https://codecov.io/bash)
 - pdoc --html finlab_crypto

notifications:
  email: 
    - koreal6803@gmail.com

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: html/finlab_crypto
  github-token: $GITHUB_TOKEN
  keep-history: false
  target_branch: gh-pages
  on:
    branch: master
